[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "etu"
version = "0.0.9"
description = "EVE Tracking Utility"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32",
    "rapidfuzz>=3.0",
]

[project.scripts]
etu = "etu.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]